export const REGISTER = "REGISTER"
export const LOGIN = "LOGIN"
export const GUEST_LOGIN = "GUEST_LOGIN"
export const REHYDRATE_USER = "REHYDRATE_USER"
export const LOGOUT_USER = "LOGOUT_USER"

export const CONNECT_SOCKET = "CONNECT_SOCKET"
export const DISCONNECT_SOCKET = "DISCONNECT_SOCKET"

export const GET_ONLINE_CONTACTS = "GET_ONLINE_CONTACTS"
export const GET_FRIENDS = "GET_FRIENDS"
export const ADD_FRIEND = "ADD_FRIEND"
export const REMOVE_FRIEND = "REMOVE_FRIEND"

export const GET_MY_GAMES = "GET_MY_GAMES"
export const GET_NOT_MY_GAMES = "GET_NOT_MY_GAMES"
export const CREATE_GAME = "START_GAME"
export const JOIN_GAME = "JOIN_GAME"
export const LEAVE_GAME = "LEAVE_GAME"
